# Generated by Django 6.0 on 2026-01-12 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0002_product_equipment'),
        ('StorageLocation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPCISEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(verbose_name='When')),
                ('event_timezone_offset', models.CharField(max_length=10)),
                ('epc_list', models.TextField(help_text='List of EPCs involved in the event, separated by commas.')),
                ('read_point', models.CharField(max_length=255)),
                ('biz_step', models.CharField(choices=[('receiving', 'Receiving'), ('picking', 'Picking'), ('shipping', 'Shipping'), ('commissioning', 'Commissioning')], max_length=100)),
                ('disposition', models.CharField(max_length=100)),
                ('biz_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StorageLocation.storagelocation', verbose_name='Business Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
