# Generated by Django 5.2.1 on 2026-01-14 06:15

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPCISEvent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epcisevent',
            name='product',
        ),
        migrations.AddField(
            model_name='epcisevent',
            name='action',
            field=models.CharField(choices=[('OBSERVE', 'Observe'), ('ADD', 'Add'), ('DELETE', 'Delete')], default='OBSERVE', max_length=10),
        ),
        migrations.AddField(
            model_name='epcisevent',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='epcisevent',
            name='event_type',
            field=models.CharField(choices=[('ObjectEvent', 'Object Event'), ('AggregationEvent', 'Aggregation Event'), ('TransactionEvent', 'Transaction Event'), ('TransformationEvent', 'Transformation Event'), ('AssociationEvent', 'Association Event')], default='ObjectEvent', max_length=50),
        ),
        migrations.AlterField(
            model_name='epcisevent',
            name='biz_location',
            field=models.CharField(help_text='SGLN for the business location', max_length=255),
        ),
        migrations.AlterField(
            model_name='epcisevent',
            name='biz_step',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='epcisevent',
            name='epc_list',
            field=models.TextField(help_text='Comma-separated GS1 Digital Links or URNs'),
        ),
        migrations.AlterField(
            model_name='epcisevent',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='epcisevent',
            name='event_timezone_offset',
            field=models.CharField(default='+00:00', max_length=6),
        ),
        migrations.AlterField(
            model_name='epcisevent',
            name='read_point',
            field=models.CharField(help_text='SGLN for the read point', max_length=255),
        ),
    ]
