# Generated by Django 4.2.3 on 2025-12-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("SerialNumberPool", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="SerialNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_serial_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "batch_lot",
                    models.CharField(
                        blank=True,
                        help_text="Assigned Batch/Lot Number at consumption.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ALLOCATED", "Allocated to Pool (Ready to use)"),
                            ("PRINTED", "Printed/Reserved by Production Line"),
                            ("CONSUMED", "Shipped/Reported Consumed"),
                            ("VOID", "Void/Scrapped (Permanently retired)"),
                        ],
                        db_index=True,
                        default="ALLOCATED",
                        max_length=10,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="serial_numbers",
                        to="SerialNumberPool.serialnumberpool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Individual Serial Number",
                "verbose_name_plural": "Individual Serial Numbers",
            },
        ),
    ]
