# Generated by Django 5.2.1 on 2025-12-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Product Code')),
                ('primary_gtin', models.CharField(max_length=14, unique=True, verbose_name='Primary GTIN')),
                ('secondary_gtin', models.CharField(blank=True, max_length=14, null=True, verbose_name='Secondary GTIN')),
                ('tertiary_gtin', models.CharField(blank=True, max_length=14, null=True, verbose_name='Tertiary GTIN')),
                ('manufactured_at', models.DateField(verbose_name='Manufactured At')),
                ('shelf_life_days', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('y', 'Year'), ('m', 'Month'), ('d', 'Day')], max_length=50, verbose_name='Unit of Measurement')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
