# Generated by Django 4.2.3 on 2025-12-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Equipment", "0002_equipment_deleted_at"),
        ("Product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="Equipment.equipment",
                verbose_name="Equipment",
            ),
        ),
    ]
