# Generated by Django 5.2.1 on 2025-12-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Equipment Name')),
                ('model_number', models.CharField(max_length=100, unique=True, verbose_name='Model Number')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial Number')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Manufacturer')),
                ('mac_address', models.CharField(max_length=17, unique=True, verbose_name='MAC Address')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('plant_name', models.CharField(max_length=255, verbose_name='Plant Name')),
                ('plant_gln', models.CharField(max_length=13, unique=True, verbose_name='Plant GLN')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
    ]
