# Generated by Django 4.2.3 on 2025-12-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
