# Generated by Django 6.0 on 2026-01-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('gln', models.CharField(help_text='Global Location Number (13 digits)', max_length=13, unique=True, verbose_name='GLN')),
                ('sub_location', models.CharField(blank=True, max_length=100, verbose_name='Sub-Location/Extension')),
                ('location_type', models.CharField(choices=[('physical', 'Physical Warehouse/Facility'), ('logic', 'Logical Location (e.g., Virtual Stock)'), ('transit', 'In Transit')], default='physical', max_length=20)),
                ('address', models.TextField(blank=True, verbose_name='Physical Address')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
            },
        ),
    ]
