# Generated by Django 5.2.1 on 2025-12-15 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True, verbose_name='Batch Number')),
                ('manufactured_at', models.DateField(verbose_name='Manufactured At')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('sampled_quantity', models.PositiveIntegerField(verbose_name='Sampled Quantity')),
                ('order_number', models.CharField(max_length=100, verbose_name='Order Number')),
                ('batch_description', models.TextField(blank=True, null=True, verbose_name='Batch Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='Product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
