# Generated by Django 4.2.3 on 2025-12-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Product", "__first__"),
        ("SerialNumberPool", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Batch Number"
                    ),
                ),
                ("manufactured_at", models.DateField(verbose_name="Manufactured At")),
                ("expiry_date", models.DateField(verbose_name="Expiry Date")),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "sampled_quantity",
                    models.PositiveIntegerField(verbose_name="Sampled Quantity"),
                ),
                (
                    "order_number",
                    models.CharField(max_length=100, verbose_name="Order Number"),
                ),
                (
                    "batch_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Batch Description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="Product.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "serial_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches_used_in",
                        to="SerialNumberPool.serialnumberpool",
                        verbose_name="Serial Number Configuration Pool",
                    ),
                ),
            ],
        ),
    ]
