# Generated by Django 5.2.1 on 2025-12-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='serial_numbers',
            field=models.TextField(blank=True, null=True, verbose_name='Serial Numbers'),
        ),
    ]
