# Generated by Django 5.2.1 on 2025-12-15 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumberPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('product_gtin', models.CharField(db_index=True, max_length=14)),
                ('start_serial_number', models.BigIntegerField(help_text='Start boundary for random generation.')),
                ('end_serial_number', models.BigIntegerField(help_text='End boundary for random generation.')),
                ('total_to_generate', models.IntegerField(help_text='Total requested count of S/Ns.')),
                ('generated_count', models.IntegerField(default=0, help_text='Count of S/Ns successfully created in the SN table.')),
                ('status', models.CharField(choices=[('NEW', 'New/Allocated'), ('ACTIVE', 'Active/Generating'), ('EXHAUSTED', 'Exhausted/Used Up'), ('VOID', 'Void/Canceled')], db_index=True, default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
