# Generated by Django 4.2.3 on 2025-12-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SerialNumberPool", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serialnumberpool",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
