# Generated by Django 4.2.3 on 2025-12-17 21:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("SerialNumberPool", "0002_serialnumberpool_updated_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="serialnumberpool",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="serialnumberpool",
            name="generated_count",
            field=models.IntegerField(default=0, help_text="Count of S/Ns created."),
        ),
    ]
